### ISSUE TITLE
Write README file

### ISSUE THREAD

**Issue by molefrog** [codehipsters/codehipsters.com#8]
No, seriously, you can have a repo without README in 2017. Include:
  - [x] Build instructions, post files structure
  - [x] List of Code Hipsters team members
  - [x] License (MIT?)
  - [x] Code style

**Comment by ujenjt** [comment]
Hey, @molefrog how to deploy the website? I've made little fix and have no idea how to do it 🤔

**Comment by molefrog** [comment]
@ujenjt Hey, thanks for mentioning this issue, I totally forgot about it. I've updated REAMDE.md file with build instructions as well as some other info.
